version: "3.3"

services:
    mysql:
        image: mysql:8.0.25
        container_name: mysql
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=teamder
        ports:
            - 3306:3306
        volumes: 
            - ./mysql_local.cnf:/etc/mysql/conf.d/mysql_local.cnf:ro
            - ./teamder-back/db:/docker-entrypoint-initdb.d
            
        networks: 
            - app-net

    back:
        depends_on: 
            - "mysql"
        build : ./teamder-back/
        ports:
            - 8080:8080
        environment:
            - MYSQL_HOST=mysql
        networks: 
            - app-net

    front:
        depends_on: 
            - "back"
        build: ./teamder-front/
        ports:
            - 4200:4200
        networks: 
            - app-net

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        networks: 
            - app-net

networks: 
    app-net: