version: "3.7"

services:
    mysql:
        image: mysql:8.0.25
        container_name: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=teamder
        volumes:
            - ./teamder-back/db:/docker-entrypoint-initdb.d

    back:
        build : ./teamder-back/
        container_name: back
        depends_on:
            - mysql
        restart: always
        ports:
            - 8080:8080
        environment:
            - MYSQL_HOST=mysql

    front:
        build: ./teamder-front/
        container_name: front
        depends_on:
            - back
        ports:
            - 4200:4200

    adminer:
        image: adminer
        container_name: adminer
        depends_on: 
            - mysql
        restart: always
        ports:
            - 8081:8080